version: '3'

# This file contains development-specific overrides
services:
  api:
    environment:
      - ASPNETCORE_URLS=http://+:${API_PORT}
      - ASPNETCORE_HTTPS_PORT=${API_PORT}
    volumes:
      - ./be:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    
  frontend:
    volumes:
      - ./fe/hotel-management:/app
      - /app/node_modules