services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  api:
    build:
      context: ./be
      dockerfile: HotelManagement.Api/Dockerfile
    container_name: hotelmanagement-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HotelManagement;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=HotelManagement
      - Jwt__Audience=HotelManagementAudience
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./fe/hotel-management
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
    container_name: hotelmanagement-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - api

volumes:
  mssql-data:
    driver: local
